unbind r 
bind r source-file ~/.tmux.conf \;

set -g prefix C-b
set -g mouse on
#set -sg terminal-overrides ",*:RGB"  # true color support
#set -g escape-time 0  # disable delays on escape sequences
#set -g repeat-time 1000  # increase "prefix-free" window

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
set -g base-index 1
# Usar modo vi en copy-mode
set -g mode-keys vi

# En copy-mode: usar 'v' para comenzar selección (como en Vim)
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
# plugins
set -g @plugin 'alexwforsythe/tmux-which-key'
# DESIGN TWEAKS
set -g status-position top
set -g status-justify centre
set -g renumber-windows on
# Theme: borders
set -g pane-border-lines simple
set -g pane-border-style "#[fg=#{@theme_primary}]"
set -g pane-active-border-style "#[fg=#{@theme_primary}]"

# --- Colores base ---
set -g @theme_fg "black"
set -g @theme_bg "default"

# --- Paleta principal ---
set -g @theme_primary "#D2A374"   # color principal
set -g @theme_secondary "#7A74D2" # color secundario
set -g @theme_alert "colour196"     # rojo para alertas
set -g @theme_inactive "colour239"  # gris tenue

# --- Status bar ---
set -g status-style "bg=#{@theme_bg},fg=#{@theme_fg},bright"
set -g status-left ""
set -g status-right "#[fg=#{@theme_primary},bright]#S"  # sesión

# --- Ventanas ---
# Theme: status (windows) #W es para nombres, ● para que sea min y #I para numeros
# si le quitas los colores aqui se ponen los del tema
# Ventanas, amarillo para el zoom
set -g window-status-format "#{?window_zoomed_flag,#[fg=#{@theme_secondary}],#[fg=#{@theme_inactive}]}●"
set -g window-status-current-format "#{?window_zoomed_flag,#[fg=#{@theme_secondary}],#[fg=#{@theme_primary}]}●"

set -g window-status-bell-style "fg=#{@theme_alert},bold"
run '~/.tmux/plugins/tpm/tpm'
